### ISSUE TITLE
Deleting Dynamic Entries?

### ISSUE THREAD

**Issue by bfutrell70** [dynamic-vml/dvml#7]
Adding entries in the sample applications work great. However, none of them cover how to remove an item from the dynamic list.

Is deleting dynamic list items supported but not shown/documented?

**Comment by cesarsouza** [comment]
Hi @bfutrell70,

Yes, it should definitely be possible to remove dynamic list items. In the sample application "[Books and authors (customized layouts)](https://dynamic-vml.github.io/samples.html#books-and-authors-customized-layouts)", you might find that each item has a "x" button associated with each dynamic item, which you can press to remove them. If possible, please download and run the application to see it running and check if it works in the way you would expect - if not, please let me know!

(if you would like to see how it works under the hood, basically the custom template contains a button which calls a javascript [function named dvml.remove passing the id of the element to remove as you can see here](https://github.com/dynamic-vml/sample-netcoreapp3.1-books-and-authors-options/blob/6d6ead6317333923eadf75fe8287853b77b0bfa5/Views/Authors/EditorTemplates/CustomItemTemplateWithMyOptions.cshtml#L16))

Hope it helps!

**Comment by bfutrell70** [comment]
That looks great - thanks for pointing out where it was.
